[font.normal]
family = "Fira Code"

[window]
decorations = "full"
opacity = 0.9
startup_mode = "Windowed"
title = "Why this no work"

 [keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]
