cookie: "sp_t=f4aae56cd6394db8fdb4b3898d544e34; sp_landing=https%3A%2F%2Fopen.spotify.com%2F%3Fsp_cid%3Df4aae56cd6394db8fdb4b3898d544e34%26device%3Ddesktop; OptanonConsent=isGpcEnabled=0&datestamp=Sun+Nov+24+2024+14%3A09%3A48+GMT%2B0100+(Central+European+Standard+Time)&version=202409.2.0&browserGpcFlag=1&isIABGlobal=false&hosts=&consentId=180400eb-026f-488f-ad33-635444635685&interactionCount=1&isAnonUser=1&landingPath=NotLandingPage&groups=s00%3A1%2Cf00%3A1%2Cm00%3A1%2Ct00%3A1%2Ci00%3A1%2CV2STACK3%3A1%2CV2STACK11%3A1%2CV2STACK20%3A1%2Cf11%3A1%2CBG181%3A1&intType=1&geolocation=DE%3BBW&AwaitingReconsent=false; OptanonAlertBoxClosed=2024-11-24T13:07:13.839Z; eupubconsent-v2=CQIl7BgQIl7BgAcABBDEBRFwAP_AAAAAAAYgJnABxC4URAFAYWowAJMgMAEUAABAQAAQAAIBAIABCBgEQAQAkAAgBACABAACGAAAIAAAAAAACAAAAEAAQIAAJADAAAAEIAAAIAAAABAAAAAAAAAgEAAAAAAAgAAEAABAiAAAAJIAEEAAAAAAAAAAIAAAAAAAAgCAAAAAAAAAAQAIQCgAAAAAAAAAAAAAARAAAQAABAAAAAAAAAAQAAAFhICoACwAKgAeABBADIANAAeABEAD0AH4AZQA54B3AHeAPgAfgBJQDiAIdAWwAvMCSAEzggAYAEgARwBOAJWAYsA_cdAZAAWABUAEEAMgA0AB4AEQAMQAegA_ACcAGUAOeAdwB3gD4AH4ARYAkoBxADqAIdAWwAvMBlgEkAJnDgBQAFwASAA_ACOAQgBKwDBAGLAMmAfuQgEAALADEAHoAc8A7gDvAOoBJACZxAACAwQlANAAWADwAIgAYgB3gD8AOoAh0BbAC8wGWASQAmcSADAAXACOAO4BKwDFgH7lICwACwAKgAggBkAGgAPAAiABiAD8AMoAc4A7wB-AEWAJKAdQA9oCHQFsALzAZYBJACZxQAUABcAEgARwBOADuAO2AwQBiwDJgH7loAIA7gAA.f_gAAAAAAAAA; sp_dc=AQBqU12CG2kNOcgVCnTHltAg0swWJIlNxfgkfhlCT-wq6RjKJ_BwBRTNY61BDVl2nHnnq_ILUBsO7Wnc7gTCFL5d9O_s7dDtfEEPRZKUQEnZWtlUGXUcGiNA6FPEJk3xjxz1g7tqLp4uK8Plln1IiXzmO8mKQEQ0dQeeRNjc5Ka9jyYDxVTrt5WdzntEcYcLbY0OGFGsvK2C3Avg_wFRayzkyImM; sp_key=f47d4a88-100c-480b-8a57-3de1ef09200c"
player: spotify
host: lyricsapi.vercel.app
ignoreErrors: true
timerInterval: 200
updateInterval: 2000
style:
  hAlignment: center
  before:
    background: ""
    foreground: ""
    bold: true
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: false
  current:
    background: ""
    foreground: ""
    bold: true
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: false
  after:
    background: ""
    foreground: ""
    bold: false
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: true
pipe:
  length: 0
  overflow: word
mpd:
  address: 127.0.0.1:6600
  password: ""
mopidy:
  address: 127.0.0.1:6680
mpris:
  players: []
