cookie: "sp_dc=AQCn6a2OeNwd_sFlmdZORojkNS08mvl08PhwNse7iMVkEQHpFiySbtVk48qIyU4pqut_uGTrDKIjCWM8OLQpEkhXgzYhl034WFPP8jGw-AHT7CXU6KO1yPXeOnmRHEUthuuPXh5ujb5wJvUSqZO9bW2tS0-h1Ywn9uYNNbWmTMVLQOKJnpULrZQ9jJZQ40Kdr_PAg8oCngybJf_3n1hgWYFLquG3; sp_key=011310fa-9d9c-4fdc-a3e0-4f467a3943f8; sp_t=cf9494109aa6323ec09b2b739ce06033; sp_m=de; sp_last_utm=%7B%22utm_campaign%22%3A%22your_account%22%2C%22utm_medium%22%3A%22menu%22%2C%22utm_source%22%3A%22spotify%22%7D; sp_gaid=0088fc69b3d6a3c026db3e2c3f637fdf2e6a370d8d66aa02d81c89; OptanonAlertBoxClosed=2023-08-28T09:52:34.162Z; sp_landing=https%3A%2F%2Fopen.spotify.com%2F%3Fsp_cid%3Dcf9494109aa6323ec09b2b739ce06033%26device%3Ddesktop; eupubconsent-v2=CPxPE-8PxPE-8AcABBENDVCgAP_AAAAAAAYgJnNBjS-vRxPj-_77brkwcY0W0cBdI-EyBgdFBKAAGboUMJ0FWGA5oEXCgKgKCAYgIUZBIAEgCCEECUEgKoEFDiGAIEiUBLEIICNAEAAAAQBAAAlQFIyAAAAAgYgECQAAgBKAAFIAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD_XWwAAAJBAC4AAQAHgAkAB-AEcAK4AbQBLgDVgHMAc4A6gCDgEcAJoATsApoB1QEegJCASKApsBT4DFgkCUABYAFYAPgBAADKAGgAagA8gCGAIgATAAngBVACwAHMAPQAfgBCACGAEsAJoAUoAyAB3wD2APgAfoBAwCKAEXgJKAkwBQQCngFXAMUAbgA4gCRAFDgLYAXmGAOgABABEACgAFQAMoAeAB6AEIAIgARwAmABXADaAHMAQwAlwBWwDmAOcAkwBOgCvgHNAOqAdkA9QB-wEhQJEAkUBTYDGQ0AMAZABTwC0CADoAAQANgAiABQACoAGUAPAA9ACEAEQAI4ATAArgBtADmAIYAS4ArYBzAHOASaAnQCdgFfAOaAdUA7IB6gD9gJCgSIBIoDGREAIAZABTxQA0AEQAKgAhABMAHMARwAr4BzQDqgH7AR6AkUBbAqAGAEMAtACQRgA4AEQAKgAhABMAFcAOYAjgBXwDmgHVAP2Aj0BIoC2BkAEAIY6BkAAsACsAHwAgABdADEAMoAaABqADyAIYAiABMACeAFUALAAXQAxABmADmAHoAPwAhgBLACYAE0AKMAUoAsYBkAGUAO8AewA_QCBgEUgIsAi4BHQCTAFBAKeAVcAtABegDFAG4AOIAi8BIICRAFDgLKAWwAvMBlg4A4AA8AC4AJAAcwA-AD8AI4ATQArgBtAEWAJcAYUA5gDnAHUAO6Ag4CEAEcAJwATsApYB1QEVAI9ASEAkUBTACmwGLEICoACwAXAAxABqAEMAJgAVQAxAB6AFKALEAZQA7wCKAFBAKeAVcAtABigEggLKIACwAmwDmAOcAjgBOAClgFpAOaAdUBHoCQgEikoCoACwAPgAxAB4AEQAJgAVQAxACGAFGAO8Ap4BVwC0AGKARMAi8BIgCygFsALzJAFAALgA5ACOAE0ANoAiwBqgDmAHcAQcAjkBSwFNALSAdUA7YCKgEegJFAYsAywpAkAAWABWAD4AQAAxgBoAGoAPIAhgCIAEwAJ4AUgAqgBYADEAGYAOYAfgBDACjAFKALGAZABlADvAH6ARYAjoBQQCrgGKANwAiYBF4CRAFDgLYAXmAywoAbAAuACQAGQAOQAfgBHACaAG0ARYAwgBqwDmAOcAdQA7gCDgEcAKWAXUA14B1QDtgI9ASKApgBTYCnwGLAAAA.f_gAAAAAAAAA; OptanonConsent=isIABGlobal=false&datestamp=Sat+Sep+02+2023+21%3A04%3A42+GMT%2B0200+(Central+European+Summer+Time)&version=6.26.0&hosts=&consentId=28602bbd-7c6f-4ea3-982b-04f63b67c7ba&interactionCount=1&landingPath=NotLandingPage&groups=s00%3A1%2Cf00%3A1%2Cm00%3A1%2Ct00%3A1%2Ci00%3A1%2CSTACK3%3A1%2CSTACK11%3A1%2CSTACK20%3A1%2Cf11%3A1%2CBG158%3A1&geolocation=DE%3BBW&AwaitingReconsent=false"
player: spotify
host: lyricsapi.vercel.app
ignoreErrors: true
timerInterval: 200
updateInterval: 2000
style:
  hAlignment: center
  before:
    background: ""
    foreground: ""
    bold: true
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: false
  current:
    background: ""
    foreground: ""
    bold: true
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: false
  after:
    background: ""
    foreground: ""
    bold: false
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: true
pipe:
  length: 0
  overflow: word
mpd:
  address: 127.0.0.1:6600
  password: ""
mopidy:
  address: 127.0.0.1:6680
mpris:
  players: []
